language: node_js
node_js:
  - "7.7.2"
before_install:
  npm install -g yarn@'>=0.22.0'
notifications:
  email:
    on_success: never
    on_failure: always
addons:
  apt:
    packages:
      - xvfb
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - yarn install
